export const EG_ARAMEX_CITIES = [
  "10th of Ramadan",
  "10Th Of Ramadan City",
  "15 Of May City",
  "Aamr Village",
  "Abasya",
  "Abdeen",
  "Abnub",
  "Abo Rawash",
  "Abo Swir",
  "ABOU SOMBO",
  "Abou Sultan",
  "Abu Hammad",
  "Abu Kebir",
  "Abu Minqar",
  "Abu Qurqas",
  "Abu Radis",
  "Abu Tesht",
  "Abu Tij",
  "Abu Zaabal",
  "Aga",
  "Agouza",
  "Ain Shams",
  "Ain Shams - East",
  "Al Abageyah",
  "Al Amaria",
  "Al Amireya",
  "Al Arish",
  "Al Atf",
  "Al Azbakeya",
  "Al Badari",
  "Al Bleena Desert",
  "Al Burlos",
  "Al Faiyum Al Gadida City",
  "Al Farafra",
  "Al Fashn",
  "Al Fath",
  "Al Haram",
  "Al Herafieen",
  "Al Husseiniya",
  "Al Ibrahimiya",
  "Al Idwah",
  "Al Maasarah",
  "Al Mahala",
  "Al Mahmmoudeya",
  "Al Manzalah",
  "Al Marg",
  "Al Matarya",
  "Al Menofiah",
  "Al Minasafur",
  "Al Monib",
  "Al Monshaah Al Kubra",
  "Al Nobariah",
  "Al Obour City",
  "AL Qanater",
  "Al Qanayat",
  "Al Qantarah Gharb",
  "Al Qarna",
  "Al Qurayn",
  "Al Qusiyyah",
  "Al Salam First",
  "Al Shorouk",
  "Al Tour City",
  "Al Wahat",
  "Al Wahat Al Dakhla",
  "Al Waili",
  "Al Waqf",
  "Al Waraq",
  "Al-Sharabiya",
  "Alexandria",
  "Ard El Lewa",
  "Armant",
  "As Santah",
  "As Sufiyyah",
  "Ashmoun",
  "Assiut",
  "Aswan",
  "At Tall Al Kabir",
  "Atfeah",
  "Attaba",
  "Awaied-Ras Souda",
  "Awlad Saqr",
  "Awsim",
  "Bab El Sharia",
  "Badr City",
  "Badrashin",
  "Bahtem",
  "Balat",
  "Bani Ebeid",
  "Bani Mazar",
  "Bani Swif",
  "Bargiel",
  "Baris",
  "Bashtil",
  "Basioun",
  "Basous",
  "Beba",
  "Beigam",
  "Belbis",
  "Belqas",
  "Benha",
  "Berkeit Sabb",
  "Bila",
  "Bir El Abd",
  "Bolak El Dakrour",
  "Borg Al Arab City",
  "Bulaq Abo Elela",
  "Cairo",
  "Cemex Area",
  "Cornish El Nile",
  "Dahab City",
  "Daher",
  "Dahshour",
  "Damanhour",
  "Damietta Port",
  "Dar Al Salam Center",
  "Dar El Salam",
  "Daraw",
  "Dayrout",
  "Deir Mawas",
  "Dekernes",
  "Dekhela",
  "Deshna",
  "Desouk",
  "Diyarb Negm",
  "Dokki",
  "Down Town",
  "Dumiatta",
  "Edfo",
  "Ehnasia",
  "Ein Al Sukhna",
  "El Ahyai",
  "El Ayat",
  "El Basatin",
  "El Dabaa",
  "El Gamaliya",
  "EL GOUNA",
  "El Granahharkana",
  "El Hassana",
  "El Hawamdiah",
  "El Idwa",
  "El King Maryout",
  "EL Korimat",
  "El Maadi",
  "El Marg",
  "El Nozha",
  "El Qantara Sharq",
  "EL rehab",
  "El Saf",
  "El Salam",
  "El Salam City",
  "El Salloum",
  "EL SAWAH",
  "El Wadi El Gadid",
  "El Wasta",
  "El Zawya El Hamra",
  "El Zeitoun",
  "El-Alamein",
  "El-Bagour",
  "El-Gamaleya City",
  "El-Ghanayem",
  "El-Hamam",
  "El-Hamoul",
  "El-Reyad",
  "El-Sayeda Zainab",
  "El-Senbellawein",
  "Elsahel",
  "Esna",
  "Ezbet El Borg",
  "Faqous",
  "Faraskour",
  "Farshout Desert",
  "Fayid",
  "Fayoum",
  "Fisal",
  "Fowah",
  "Future City",
  "Garden City",
  "Ghamrah",
  "Giza",
  "Hadaba",
  "Hadayek El Qobah",
  "Hay Elnour",
  "Heliopolis",
  "Helwan",
  "High Dam",
  "Hihya",
  "Hikestab",
  "Hurghada",
  "Ibshaway",
  "Imbaba",
  "Inshas",
  "Isbico",
  "Ismailia",
  "Itsa",
  "Izbat Shaheen",
  "Juhaynah Al-Gharbyah Desert",
  "Kafr Al Musaylhah",
  "Kafr Al Sheikh",
  "Kafr El-Hamam",
  "Kafr El-Zayat",
  "Kafr Saad",
  "Kafr Saqr",
  "Kafr Shokr",
  "Kaha",
  "Kasr El Einy",
  "Katamiah",
  "Khanka",
  "Kharga",
  "Kom Ombo",
  "Luxour",
  "Maadi",
  "Madinaty",
  "Madinet Al Matareyah",
  "Madinet Tami Al Amdid",
  "Maghaghah",
  "Mallawi",
  "Manfalut",
  "Manial El Rodah",
  "Manil Shihah",
  "Mansheyt Naser",
  "Mansoura",
  "Marabella",
  "Maraqia",
  "Marinah",
  "Markaz Abu Al Matamir",
  "Markaz Abu Humus",
  "Markaz Ad Delingat",
  "Markaz Akhmim",
  "Markaz Al Belina",
  "Markaz Al Maraghah",
  "Markaz Al Monshaah",
  "Markaz Ar Rahmaneyah",
  "Markaz Edko",
  "Markaz Girga",
  "Markaz Housh Eissa",
  "Markaz Itay Al Baroud",
  "Markaz Juhaynah Al-Gharbyah",
  "Markaz Kafr El-Dawar",
  "Markaz Kom Hamada",
  "Markaz Saqaltah",
  "Markaz Shubrakhat",
  "Markaz Tahta",
  "Markaz Tama",
  "Marsa Alam",
  "Marsa Matrouh",
  "Mashtool El Souk",
  "Matay",
  "Meet Ghamr",
  "Menia City",
  "Menouf City",
  "Menyet El-Nasr",
  "Metobas",
  "Minya El Qamh",
  "Mohandiseen",
  "Mokattam",
  "Moustorod",
  "Naama Bay",
  "Nabaroh",
  "Nag Hamadi",
  "Nakhl",
  "Naqadah",
  "Nasr City",
  "Nasr El Nouba",
  "Nasser",
  "New Assiut",
  "New Cairo",
  "New Capital City",
  "New Damietta City",
  "New Minya City",
  "New Salhia",
  "New Sohag City",
  "North Coast",
  "Nuwibaa",
  "October City",
  "Omranya",
  "Port Fouad",
  "Port Said",
  "Pyramids Gardens",
  "Qalioub",
  "Qaliubia",
  "Qasr El Nil",
  "Qena",
  "Qesm Al Qosimah",
  "Qesm Remanah",
  "Qift",
  "Qillin",
  "Qism El Qoseir Desert",
  "Qism El-Khalifa",
  "Qotour",
  "Quesna",
  "Qus",
  "Rafah",
  "Ramsis",
  "Ras Elbar",
  "RAS GHAREB",
  "Ras Seidr",
  "Ras Shoqeir",
  "Rod El Farag",
  "Sadat City",
  "Safaga",
  "Sahel Selim",
  "Saint Catherine",
  "Salh Hashes",
  "Samalut",
  "Samannoud",
  "Samasta",
  "Saqara",
  "Sedi Kreir",
  "Shalateen",
  "Sharm El Sheikh",
  "Sharq At Tafriah",
  "Shebin El Koum",
  "Sheikh Zayed City",
  "Sheikh Zuweid",
  "Sherbeen",
  "Shibin Al Qanater",
  "Shubra",
  "Shubra El Kheima",
  "Shubra Ment",
  "Shuhada",
  "Sidfa",
  "Sidi Barrani",
  "Sidi Salem",
  "Sinnuris",
  "Siwa",
  "sohag City",
  "Suez",
  "Taba City",
  "Taha Al Sbah",
  "Tala",
  "Talkha",
  "Tamiya",
  "Tanta",
  "Tebin",
  "Tiba",
  "Torah",
  "Toshka",
  "Toukh",
  "Wadi Dar Al Zaraey",
  "Wadi El Natroun",
  "Wadi Hof",
  "Warraq Al Hadar",
  "Youssef Al Seddik",
  "Zakazik",
  "Zamalek",
  "Zarka City",
  "Zawyet Sidi Abd El-Ati",
  "Zefta",
] as const;
