import { defineField, defineType } from "sanity";

export const conversionRescueSettings = defineType({
  name: "conversionRescueSettings",
  title: "Conversion rescue popup",
  type: "document",
  groups: [
    { name: "behavior", title: "Behavior", default: true },
    { name: "discount", title: "Discount" },
    { name: "content", title: "Popup content" },
  ],
  fields: [
    defineField({
      name: "enabled",
      title: "Enable popup",
      description: "Shows a timed rescue popup for visitors who browse without buying.",
      type: "boolean",
      initialValue: false,
      group: "behavior",
    }),
    defineField({
      name: "delaySeconds",
      title: "Show after seconds",
      description: "Recommended: 30 seconds. It is hidden on checkout, cart, order confirmation, and Studio pages.",
      type: "number",
      initialValue: 30,
      validation: (Rule) => Rule.required().min(10).max(300),
      group: "behavior",
    }),
    defineField({
      name: "dismissDays",
      title: "Hide after close for days",
      description: "How long to hide the popup after the visitor closes it.",
      type: "number",
      initialValue: 7,
      validation: (Rule) => Rule.required().min(1).max(60),
      group: "behavior",
    }),
    defineField({
      name: "targetPath",
      title: "Main button target",
      description: "Recommended: /checkout. The current language is kept automatically.",
      type: "string",
      initialValue: "/checkout",
      validation: (Rule) => Rule.required(),
      group: "behavior",
    }),
    defineField({
      name: "discountCode",
      title: "Deprecated fallback code",
      description: "Hidden legacy fallback. Current codes are random, signed, time-limited, and browser-bound.",
      type: "string",
      hidden: true,
      group: "discount",
    }),
    defineField({
      name: "discountPercent",
      title: "Discount percent",
      description: "CMS controls the percentage. The website generates a new random secure code for each visitor.",
      type: "number",
      initialValue: 5,
      validation: (Rule) => Rule.required().min(1).max(90),
      group: "discount",
    }),
    defineField({
      name: "codePrefix",
      title: "Code prefix",
      description: "Short brand prefix before the random code, for example NAT.",
      type: "string",
      initialValue: "NAT",
      validation: (Rule) => Rule.max(8),
      group: "discount",
    }),
    defineField({
      name: "codeValidityHours",
      title: "Code validity hours",
      description: "How long each generated code stays valid. Recommended: 24 hours.",
      type: "number",
      initialValue: 24,
      validation: (Rule) => Rule.required().min(1).max(168),
      group: "discount",
    }),
    defineField({
      name: "discountLabel",
      title: "Discount label",
      description: "Shown on the popup badge. Example: 5% OFF.",
      type: "string",
      initialValue: "5% OFF",
      validation: (Rule) => Rule.required(),
      group: "content",
    }),
    defineField({
      name: "eyebrow",
      title: "Small title",
      type: "string",
      initialValue: "استنى",
      validation: (Rule) => Rule.required(),
      group: "content",
    }),
    defineField({
      name: "title",
      title: "Main title",
      type: "string",
      initialValue: "خد خصم لو كملت الأوردر دلوقتي",
      validation: (Rule) => Rule.required(),
      group: "content",
    }),
    defineField({
      name: "description",
      title: "Description",
      type: "text",
      rows: 2,
      initialValue: "استخدم الكود قبل الدفع، والخصم هيتطبق في checkout.",
      group: "content",
    }),
    defineField({
      name: "ctaLabel",
      title: "Main button label",
      type: "string",
      initialValue: "كمل الأوردر بالخصم",
      validation: (Rule) => Rule.required(),
      group: "content",
    }),
    defineField({
      name: "copyLabel",
      title: "Copy button label",
      type: "string",
      initialValue: "انسخ الكود",
      group: "content",
    }),
    defineField({
      name: "copiedLabel",
      title: "Copied label",
      type: "string",
      initialValue: "اتنسخ",
      group: "content",
    }),
    defineField({
      name: "declineLabel",
      title: "Decline label",
      type: "string",
      initialValue: "لا أريد",
      group: "content",
    }),
  ],
  preview: {
    select: {
      title: "title",
      enabled: "enabled",
      percent: "discountPercent",
    },
    prepare({ title, enabled, percent }) {
      return {
        title: title || "Conversion rescue popup",
        subtitle: `${enabled ? "Enabled" : "Disabled"} - ${percent || 0}% discount`,
      };
    },
  },
});
